# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 * * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          retries: 3
          retries_delay: 300
          retries_output_action: 5
          retries_delay_output_action: 120
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: UTC
          plugin_languages: yes
          plugin_languages_other: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_lines: yes
          plugin_lines_sections: history
          plugin_followup: yes
          plugin_stars: yes
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 30
          plugin_habits_facts: yes
          plugin_habits_from: 365
          plugin_calendar: yes
          plugin_calendar_limit: 5
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_activity: yes
          plugin_activity_days: 365
          plugin_licenses: yes
          plugin_licenses_ratio: yes
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors-graphs, os-graphs
          plugin_wakatime_languages_ignored: markdown, plaintext, text, xml, yaml, JSON
          plugin_wakatime_days: 365
          plugin_traffic: yes
          plugin_gists: yes
